# Generated by Django 3.1.4 on 2021-01-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body_text',
            new_name='body_txt',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='short_text',
            new_name='short_txt',
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
